import uuid

from script.appservice.feature.report.report import Match
from script.infrastructure.repository.base.raw_data_maintance import RawDataMaintance
from script.infrastructure.utility.handler.singleton import delete_singleton

testcase = [
    #
    {101: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [], 'blocked_times': 0,
           'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [], 'blocked_times': 0,
           'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    #
    {101: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     102: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [],
           'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 105, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 106, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 107, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 208, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 109, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 110, 'tags': []},
                                       {'gender': 1, 'time': 5, 'user_id': 211, 'tags': []}],
           'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                     'boring': 1}},
     202: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}}},
    # php女 《 php男
    {202: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     203: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     204: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     205: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     206: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     207: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     208: {'gender': 1, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     },
    # php女+usa女《 php男
    {202: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     203: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     204: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     205: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 6, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {'gender': 2},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     206: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {'gender': 2},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     207: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     208: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     },
    # php女 《 php男, php女+usa女 》 php男
    {202: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     203: {'gender': 2, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     204: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     205: {'gender': 2, 'country': 'usa', 'num_consecutive_fail': 6, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     206: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 5, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {'gender': 2},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     207: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     208: {'gender': 1, 'country': 'php', 'num_consecutive_fail': 0, 'self_blocklist': [103],
           'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
           'match_map_last_30_times': [{'gender': 0, 'time': 5, 'user_id': 131, 'tags': []},
                                       {'gender': 0, 'time': 5, 'user_id': 199, 'tags': []}],
           'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
     },
    # php女 》 php男 ，php女《 php男+usa男
    {},
    # php女 》 php男 + usa男
    {},
    # php女 《 php男， usa男
    {},
    # php女 《 php男， usa女《usa男
    {},
    # php女 《 php男， usa女 》usa男
    {},

    # php女  》php男
    {},
    # php女  》php男， usa女
    {},
    # php女  》php男， usa男
    {},
    # php女 》 php男 ，php女《 php男+usa男
    {},
    # php女 》 php男 + usa男
    {},
    # php女 》 php男， usa女 》usa男
    {},
    # php女 》 php男， usa女《 usa男
    {},
    #
    {
        101: {'gender': 0, 'country': 'usa', 'activity_score': 8, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 23, 'pub_blocked': 0,
              'targeted_match': {'gender': 1},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 105},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 106},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 107},
                                          {'gender': 1, 'time': 5, 'tags': [], 'user_id': 208},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 109},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 110},
                                          {'gender': 1, 'time': 5, 'tags': [], 'user_id': 211}],
              'evaluation_tags_top_5': {'knowledgeable': 10, 'handsome': 9, 'interesting': 7, 'lovely': 4,
                                        'boring': 1}},
        102: {'gender': 0, 'country': 'usa', 'activity_score': 3, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 7, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 112}],
              'evaluation_tags_top_5': {'handsome': 3, 'knowledgeable': 1, 'boring': 1}},
        103: {'gender': 0, 'country': 'php', 'activity_score': 5, 'current_experience': {}, 'num_consecutive_fail': 1,
              'self_blocklist': [], 'blocked_times': 6, 'match_times': 33, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 113},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 114},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 115},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 116},
                                          {'gender': 1, 'time': 5, 'tags': [], 'user_id': 217},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 118},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 109}],
              'evaluation_tags_top_5': {'disgusting': 14, 'nasty': 8, 'boring': 7, 'lovely': 1}},
        104: {'gender': 0, 'country': 'usa', 'activity_score': 3, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [103], 'blocked_times': 1, 'match_times': 14, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 119},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 120}],
              'evaluation_tags_top_5': {'handsome': 10, 'knowledgeable': 4, 'boring': 2}},
        105: {'gender': 0, 'country': 'php', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        199: {'gender': 0, 'country': 'usa', 'activity_score': 8, 'current_experience': {}, 'num_consecutive_fail': 11,
              'self_blocklist': [], 'blocked_times': 2, 'match_times': 6, 'pub_blocked': 1,
              'targeted_match': {'gender': 1},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 122},
                                          {'gender': 1, 'time': 5, 'tags': [], 'user_id': 202}],
              'evaluation_tags_top_5': {'disgusting': 3, 'nasty': 3, 'boring': 2}},
        198: {'gender': 0, 'country': 'usa', 'activity_score': 9, 'current_experience': {}, 'num_consecutive_fail': 5,
              'self_blocklist': [], 'blocked_times': 4, 'match_times': 12, 'pub_blocked': 1, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 128},
                                          {'gender': 1, 'time': 5, 'tags': [], 'user_id': 217}],
              'evaluation_tags_top_5': {'disgusting': 11, 'nasty': 10, 'boring': 2}},
        300: {'gender': 1, 'country': 'php', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        150: {'gender': 0, 'country': 'usa', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        151: {'gender': 0, 'country': 'php', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        152: {'gender': 0, 'country': 'usa', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        153: {'gender': 0, 'country': 'php', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        154: {'gender': 0, 'country': 'php', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        155: {'gender': 0, 'country': 'usa', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 3,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        156: {'gender': 0, 'country': 'usa', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0,
              'targeted_match': {'gender': 1}, 'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        157: {'gender': 0, 'country': 'usa', 'activity_score': 0, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 0, 'pub_blocked': 0,
              'targeted_match': {'gender': 1}, 'match_map_last_30_times': [], 'evaluation_tags_top_5': {}},
        208: {'gender': 1, 'country': 'php', 'activity_score': 8, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 32, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 119},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 101}],
              'evaluation_tags_top_5': {'hot': 27, 'interesting': 7}},
        217: {'gender': 1, 'country': 'php', 'activity_score': 7, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 45, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 1, 'time': 5, 'tags': [], 'user_id': 198},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 103}],
              'evaluation_tags_top_5': {'interesting': 26, 'lovely': 12, 'hot': 10, 'boring': 4, 'knowledgeable': 2}},
        202: {'gender': 1, 'country': 'php', 'activity_score': 5, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [103], 'blocked_times': 0, 'match_times': 40, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 131},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 199}],
              'evaluation_tags_top_5': {'boring': 22, 'lovely': 20, 'interesting': 7, 'disgusting': 6}},
        231: {'gender': 1, 'country': 'php', 'activity_score': 5, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [], 'blocked_times': 0, 'match_times': 17, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 119},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 120}],
              'evaluation_tags_top_5': {'hot': 13, 'lovely': 9}},
        232: {'gender': 1, 'country': 'usa', 'activity_score': 5, 'current_experience': {}, 'num_consecutive_fail': 0,
              'self_blocklist': [104], 'blocked_times': 0, 'match_times': 10, 'pub_blocked': 0, 'targeted_match': {},
              'match_map_last_30_times': [{'gender': 0, 'time': 5, 'tags': [], 'user_id': 119},
                                          {'gender': 0, 'time': 5, 'tags': [], 'user_id': 120}],
              'evaluation_tags_top_5': {'hot': 4, 'lovely': 2, 'interesting': 2}}},
]



if __name__ == '__main__':

    class Test(Match):

        def __init__(self, test_case):
            super().__init__()
            self.test_case = test_case

        def to_do(self):
            delete_singleton()
            group_id = uuid.uuid4().hex
            raw_data_maintance = RawDataMaintance()
            raw_data_maintance.match_group_data = self.test_case
            self.start_match(group_id, raw_data_maintance)

    for i in testcase:
        match = Test(i)
        match.to_do()